### ISSUE TITLE
Cannot delete infrastructure when credentials data keys a re missing in secret

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-alicloud#12]
From https://github.com/gardener/gardener-extensions/issues/577

> If the account secret does not contain a service account json, the cluster can for sure not be created.
But when trying to delete such a cluster this fails because of the same reason:
> ```
> Waiting until shoot infrastructure has been destroyed
> Last Error
> task "Waiting until shoot infrastructure has been destroyed" failed: Failed to delete infrastructure: Error deleting infrastructure: secret shoot--berlin--rg-kyma/cloudprovider doesn't have a service account json
> ```

> It is the same also for the other providers. This is not something specific to gcp.

**Comment by minchaow** [comment]
Hi @rfranzke: I noticed the PR #41 probably cannot fix the issue completely. I saw you are using `stateIsEmpty` and `configExists` to check if need to do the following cleaning up task. After I had a try, I found that even if the invalid credentials is used, configmaps `*.infra.tf-config` and `*.infra.tf-state` , and one secret `*.infra.tf-vars`  would still be created, but also the content in `*.infra.tf-state` is not empty, so the judgement of `stateIsEmpty` and `configExists` will not work, and the following cleaning up work would be executed and be blocked.

Maybe I misunderstand this part of logic, please correct me if I was wrong, thanks

**Comment by rfranzke** [comment]
Hm, can you explain more? The only condition is to check that the state is empty: https://github.com/gardener/gardener-extension-provider-alicloud/pull/41/files#diff-75d4163a5866d623777bdd16e47e51a5R484
If the state is empty then the configuration will be cleaned up and the `Delete()` function will exit. Where do you see usage of `configExists`?

The `IsStateEmpty` function returns `true` if the state does not exist or has length 0.

> but also the content in *.infra.tf-state is not empty,

That's strange, why is it not empty if the credentials are invalid? Can you share how such a state looks like? Maybe it's different with Alicloud TF provider plugin, I didn't see that the state gets filled with anything for other providers.

**Comment by rfranzke** [comment]
@minchaow shared via Slack the following state:

```
terraform.tfstate: |
    {
      "version": 4,
      "terraform_version": "0.12.9",
      "serial": 3,
      "lineage": "b156df23-3493-1eeb-f398-4a5073a18b38",
      "outputs": {
        "key_pair_name": {
          "value": "shoot--core--pesgc5qflv-ssh-publickey",
          "type": "string"
        },
        "vpc_cidr": {
          "value": "10.250.0.0/16",
          "type": "string"
        }
      },
      "resources": [
        {
          "mode": "managed",
          "type": "alicloud_eip_association",
          "name": "eip_natgw_asso_z0",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_nat_gateway",
          "name": "nat_gateway",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_security_group",
          "name": "sg",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_security_group_rule",
          "name": "allow_all_internal_tcp_in",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_security_group_rule",
          "name": "allow_all_internal_udp_in",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_security_group_rule",
          "name": "allow_k8s_tcp_in",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_snat_entry",
          "name": "snat_z0",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "alicloud_vswitch",
          "name": "vsw_z0",
          "provider": "provider.alicloud",
          "instances": []
        },
        {
          "mode": "managed",
          "type": "null_resource",
          "name": "outputs",
          "provider": "provider.null",
          "instances": [
            {
              "schema_version": 0,
              "attributes": {
                "id": "1253644501264644069",
                "triggers": {
                  "recompute": "outputs"
                }
              }
            }
          ]
        }
      ]
```

It seems that the Alicloud TF plugin modifies the state even it cannot do anything with the Alicloud API because the credentials are invalid.

So, yes, indeed, the implemented solution doesn't work for Alicloud.

>  OK, anyways, so imho it makes sense to reach out to Alicloud TF plugin maintainers and ask them why this is/contribute that it doesn’t happen anymore. This doesn’t help you now and takes more time, so you’re right, some smarter handling could be implemented by the Gardener Alicloud extension.

@minchaow will follow up.
