### ISSUE TITLE
Machine-controller-manager provider for Alicloud

### ISSUE THREAD

**Issue by hardikdr** [gardener/gardener-extension-provider-alicloud#137]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority normal
/platform alicloud

**What would you like to be added**: As discussed with @minchaow, opening the issue here to support alicloud provider for machine-controller-manager.

Please find the steps to add support for a new provider here: https://github.com/gardener/machine-controller-manager/blob/master/docs/development/cp_support_new.md

Already available provider for reference: 
- https://github.com/gardener/machine-controller-manager-provider-vsphere
- https://github.com/gardener/machine-controller-manager-provider-gcp

**Why is this needed**: This is needed as part of the extensibility of MCM.

**Comment by hardikdr** [comment]
/assign @minchaow 

cc @prashanth26

**Comment by ialidzhikov** [comment]
@minchaow , can this be closed now?

Ref https://github.com/gardener/gardener-extension-provider-alicloud/pull/224

**Comment by prashanth26** [comment]
Yes, this can be closed now.

/close
