### ISSUE TITLE
Cloud Controller Manager can't access alicloud provider API server

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#30]
**What happened**:
In Frankfurt region, Cloud Controller Manager can't access Cloud API server https://slb.eu-central-1.aliyuncs.com. Recently, slb.eu-central-1.aliyuncs.com is resolved to 100.100.0.18, which is a non-public IP address. 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Nice catch @jia-jerry .
We saw that `allow-to-public-networks` netpol is problematic and does not allows traffic to `100.100.0.18`.
Do you have any plans for mitigation?
