### ISSUE TITLE
Make encrypted option to true for system or data disk by default.

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#386]
**How to categorize this issue?**

/area security
/kind enhancement
/priority 3
/platform alicloud

**What would you like to be added**:
Now, system disk or data disk of new created shoot is unencrypted by default.
For data disk of new created shoot, it should be set as encrypted.
For system disk of new created shoot, if the image is custom image(this is a precondition for alicloud to encrypt a system disk), it should be set as encrypted.

**Why is this needed**:

**Comment by vlerenc** [comment]
Thank you @jia-jerry!
