### ISSUE TITLE
Enforce client side ratelimit for DNS Record Controller

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#387]
**How to categorize this issue?**

/area robustness
/kind enhancement
/priority 3
/platform alicloud

**What would you like to be added**:
We need to enforce client side ratelimit for DNS Record Controller. We already encountered AliCloud API [ratelimit issue](https://github.com/gardener/external-dns-management/issues/71) before. [TokenBucketRateLimiter ](https://github.com/kubernetes/client-go/blob/master/util/flowcontrol/throttle.go#L63) could be a reference.
**Why is this needed**:

**Comment by stoyanr** [comment]
@jia-jerry Unfortunately I won't be able to work on this. It could be added similarly to how it has been done for AWS with https://github.com/gardener/gardener-extension-provider-aws/pull/425 and https://github.com/gardener/gardener-extension-provider-aws/pull/458.

/unassign
