### ISSUE TITLE
Upgrade Snapshotter CSI controller to latest version

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-alicloud#435]
**How to categorize this issue?**

/area TODO
/kind enhancement
/platform alicloud

**What would you like to be added**:

**Why is this needed**:

**Comment by jia-jerry** [comment]
It seems the snapshot contontroller is not needed.

**Comment by EmoinLanyu** [comment]
There is already a [PR](https://github.com/gardener/gardener-extension-provider-alicloud/pull/473) updating csi-snapshotter by @acumino , I will first hold his pr and add the corresponding validating webhook server before updating.
