### ISSUE TITLE
admission-alicloud's mutator should select only alicloud Shoots

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-alicloud#553]
**How to categorize this issue?**

/area quality
/kind bug
/platform alicloud

**What happened**:
On a landscape all my AWS Shoots fail to be reconciled with reason
```
task "Deploying internal domain DNS record" failed: Internal error occurred: failed calling webhook "shoots.mutation.alicloud.provider.extensions.gardener.cloud": failed to call webhook: Post "https://gardener-extension-admission-alicloud.garden/webhooks/mutate/shoots?timeout=10s": dial tcp: lookup gardener-extension-admission-alicloud.garden on 10.116.48.10:53: no such host
```

The webhook selects all Shoots.

```yaml
  name: shoots.mutation.alicloud.provider.extensions.gardener.cloud
  namespaceSelector: {}
  objectSelector: {}
```

**What you expected to happen**:
The webhook should benefit from https://github.com/gardener/gardener/pull/5472 (ref https://github.com/gardener/gardener/blob/v1.61.0/docs/extensions/admission.md) and should select only alicloud Shoots.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.42.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
cc @shafeeqes

**Comment by shafeeqes** [comment]
xRef https://github.com/gardener/gardener/issues/4932
