### ISSUE TITLE
Problems during make check

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener-extension-provider-alicloud#68]
**What happened**:
Running `make check` returns the following errors:
```
Executing check-generate
SA1019: Package github.com/gardener/gardener/test/integration/framework is deprecated: this is the deprecated gardener testframework. Use gardener/test/framework instead
```
```
Executing golangci-lint
Checking for format issues with gofmt
Unformatted files detected:
pkg/imagevector/packrd/packed-packr.go
```
**What you expected to happen**:
`make check` to run without errors

**How to reproduce it (as minimally and precisely as possible)**:
1. Checkout the master branch.
2. Execute `make check`

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Did you executed `make install-requirements`?

**Comment by ialidzhikov** [comment]
I cannot reproduce
```
$ make check-generate
> Generate Check
$ echo $?
0
```

**Comment by plkokanov** [comment]
> Did you executed make install-requirements?

Nope, thanks alot that fixed it :)
